### ISSUE TITLE
can you fix the thug shaking bug

### ISSUE THREAD

**Issue by rwf93** [2048khz-gachi-rmx/botto_js#1]
title

**Comment by 2048khz-gachi-rmx** [comment]
sorry the `thugshaker` package depends on the `rumpshaker` package which was part of a supply chain attack recently and wiped my hard drive and replaced all gtarkov luas with 
```
🍑🟫 ⬆️⬇️⬆️⬇️⬆️⬇️⬆️⬇️⬆️⬇️⬆️⬇️⬆️⬇️
```
you can put a bounty on this bug (min 100g) if you want it fixed

**Comment by rwf93** [comment]
![_8Xq29Yx_400x400](https://github.com/2048khz-gachi-rmx/botto_js/assets/22036195/bb0ee12e-cb11-4aae-8486-5339b9c06c47)
